server:
    port: 9091



eureka:
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: RESTAURENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3307/restaurentdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
