
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka
spring:
  profiles:
    active: dev
datasource:
  url: jdbc:mysql://localhost:3307/restaurentdb
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver